<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>02bdcf5f-74cb-4de3-87ee-152762882da7</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ftgo.Auth\Ftgo.Auth.csproj" />
  </ItemGroup>
</Project>
